### ISSUE TITLE
Couldn't run the main.py

### ISSUE THREAD

**Issue by AkiMosi** [nrajasin/Network-intrusion-dataset-creator#12]
Entering the command ``` python main.py```
leads to this
```shell
Running as user "root" and group "root". This could be dangerous.
Exception in thread packet capture data:
Traceback (most recent call last):
  File "/home/akimosi/anaconda3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "main.py", line 56, in run
    json_obj = json.loads(json_str.strip())
  File "/home/akimosi/anaconda3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/akimosi/anaconda3/lib/python3.7/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 146 column 4 (char 5236)

```
and freezes until we stop it.

**Comment by freemansoft** [comment]
The tshark format has changed since 2018.  SSL became TLS, and other changes

Try this fork.  https://github.com/freemansoft/Network-intrusion-dataset-creator
* I never used requirements.txt to install dependencies.  My local python3 install didn't need anything.
* The requirements.txt should be dumped and rebuilt based on needs in a completely clean environment
